fix several bugs in oncokb annotation scripts and improve code robustness
cBioPortal/cbioportal pull request #10049
Opened 2023-02-27 12:44 UTC by SRodenburg

I ran into several issues while using these scripts. Can now also use local `*.json` files for gene symbol resolving.
Code improvements to handle edge cases in the data.

2023-02-27 12:47 UTC, SRodenburg commented on core/src/main/scripts/importer/importOncokbDiscreteCNA.py
> +                continue
this is prob the most important change

2023-02-27 13:43 UTC, oplantalech requested changes

2023-02-27 14:32 UTC, SRodenburg commented on core/src/main/scripts/importer/importOncokbDiscreteCNA.py
> +                continue
just FYI, the cbio importer also rounds non-integer values (e.g. 1.5 -> 2) so this follows that same logic.
Values other than -2, 1, 1, 2 are skipped by default.

2023-02-27 15:01 UTC, oplantalech approved these changes

2023-02-27 16:14 UTC, SRodenburg commented
@inodb can we merge this with tomorrow's release? Thanks :)

2023-02-28 18:57 UTC, pvannierop approved these changes
Nice addition!

2023-03-02 13:11 UTC, SRodenburg commented
Any clue why the e2e tests are failing on Keycloak? seems unrelated to this PR

2023-03-07 15:48 UTC, merged