Use RSA256 algorithm for SAML2 authN statement singing
cBioPortal/cbioportal pull request #10387
Opened 2023-09-15 10:11 UTC by pvannierop

# Problem
Keycloak 22 does not allow login from cBioPortal because the authN request is signed with SHA1 algorithm. Keycloak dropped support for SHA1 because it is insecure.

# Solution
Configure cBioPortal to sign with RSA-256 algorithm.

This PR will reconfigure cBioPortal to use RSA-256 according to this [blogpost](https://myshittycode.com/2016/02/23/spring-security-saml-replacing-sha-1-with-sha-256-on-signature-and-digest-algorithms/).

2023-09-15 14:35 UTC, dippindots commented
Inviting @n1zea144 for review, @pvannierop with this change, will cbioportal be able to use keycloak v22?

2023-09-27 12:59 UTC, pvannierop commented
@dippindots Yes, this change is needed to operate with Keycloak v22. I tested backwards compatibility with Keycloak v16.

2023-09-27 14:39 UTC, inodb commented
I'll double check our keycloak version and then merge

2023-10-03 16:50 UTC, inodb commented
Looks like we're on v9 btw:

```
keycloak                                        default         1               2023-07-05 12:32:48.814831 -0700 -0700  deployed        keycloak-9.0.1          11.0.0
```
Gonna try with that version and retry

2023-10-03 19:31 UTC, inodb commented
It seems to work on our genie instance

@pvannierop it looks like there is some issue in the core tests tho: https://github.com/cBioPortal/cbioportal/actions/runs/6395996176/job/17360869425. Any clue?

2023-10-03 19:47 UTC, inodb requested changes
Some issue in core tests but otherwise looks good

2023-10-04 14:36 UTC, merged