Added setting for python-specific connection URL
cBioPortal/cbioportal pull request #10439
Opened 2023-10-19 09:02 UTC by Floris-Hyve

### Problem:

Standard database connection string does not work when using mySQL python connector for migration. 

### Fix: 

Added Python-specific connection URL, and implemented it in the get_database_properties function, so the correct URL is selected for the migration script.

Input URL is given in the portal.properties:

`db.connection_string_python=`

2023-10-23 08:30 UTC, pvannierop requested changes
Some small changes.

2023-10-23 08:30 UTC, pvannierop commented on docs/deployment/customization/portal.properties-Reference.md
> +Setting for python-specific connection URL in order to connect using both python and java at the entrypoint.
```suggestion
Setting that allow a python-specific database connection URL that is different from the connection URL used by Java. This allows, for instance, to migrate the database with different connection properties in the docker entry point script.
```

2023-10-23 08:30 UTC, pvannierop commented on docs/deployment/customization/portal.properties-Reference.md
> +```
```suggestion
The format of the `db.connection_string_python` is: 

``` 
jdbc:mysql://localhost:3306/cbiodb

``` 
```

The format of the `db.connection_string_python` is identical to `db.connection_string`.

2023-10-23 08:30 UTC, pvannierop commented on src/main/resources/portal.properties.EXAMPLE
> +# Added connection string for when both python and java connections are used in the entrypoint
Please better describe what this setting __does__, not only when it is used.

2023-11-01 10:32 UTC, pvannierop requested changes
Two proposed changes:
1. Clean up the commits (now there are 7!)
2. Harmonize information on precedence of the URL properties.

2023-11-01 10:32 UTC, pvannierop commented on src/main/resources/portal.properties.EXAMPLE
> +# db.connection_string_python= jdbc:mysql://cbioDB:3306/cbioportal
The comment on precedence should also  be made in the portal.properties-reference.md

2023-12-06 16:14 UTC, JREastonMarks commented
From an RFC72 (6.0) perspective the core module has been moved out of the cbioportal code base and into its own code base here: https://github.com/cBioPortal/cbioportal-core

@pvannierop can you create another PR for this in that repo? That way it will work in both 5.X and 6.X versions of cBioPortal.

2024-01-22 15:40 UTC, alisman commented
@JREastonMarks can you provide direction on how re-target this PR in a 6.0 world.

2024-01-22 17:01 UTC, JREastonMarks commented
Hi @Floris-Hyve,
With the release of 6.0.0 (RFC72) we moved a lot of code around and updated some of the files that you reference in this PR. The core module has been moved to its own repository: https://github.com/cBioPortal/cbioportal-core. If you move this PR to the core package it should still be a quick change. Please let me know if you need any help.

2024-01-23 15:24 UTC, JREastonMarks commented
Closing but willing to reopen if needed.

2024-01-23 15:24 UTC, closed without merging