Documentation for the 'priority_studies' feature in portal.properties.
cBioPortal/cbioportal pull request #10441
Opened 2023-10-23 12:05 UTC by sowmiyaa-kumar

2023-10-25 14:09 UTC, MatthijsPon requested changes
Thanks for looking into this @sowmiyaa-kumar! Just some small stuff to improve clarity

2023-10-25 14:09 UTC, MatthijsPon commented on docs/deployment/customization/portal.properties-Reference.md
> +By default, the studies loaded onto a local cBioPortal instance are organized alphabetically on the basis of their category (i.e. Breast >> Other).
```suggestion
By default, the studies loaded into a local cBioPortal instance are organized based on their cancer type (i.e. Breast >> Other).
```

2023-10-25 14:09 UTC, MatthijsPon commented on docs/deployment/customization/portal.properties-Reference.md
> +The value to this variable will force study ids and categories to the top of the study selector view. The format for the string should be category1#study1a,study1b,study1c;category2#study2 (for e.g.
```suggestion
The value of this variable create a custom category with studies on the top of the study selector view. The format for the string should be category1#study1a,study1b,study1c;category2#study2 (e.g., PanCancer Studies#msk_impact_2017), where the ``category`` can be any string and the ``study`` should be the study ID of the required uploaded study. 
```
Using the public portals prio will improve clarity, I think :)

2023-10-27 15:28 UTC, inodb approved these changes
LGTM!

2023-10-27 15:29 UTC, merged