(rebased) Refactor sort/search/pagination for ClinicalData table endpoint
cBioPortal/cbioportal pull request #10766
Opened 2024-04-22 19:59 UTC by dippindots

Fix # (see https://help.github.com/en/articles/closing-issues-using-keywords)

Describe changes proposed in this pull request:
- a
- b

# Checks
- [ ] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). We can fix this during merge by using a squash+merge if necessary
- [ ] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!
- [ ] Make sure your PR has one of the labels defined in https://github.com/cBioPortal/cbioportal/blob/master/.github/release-drafter.yml

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [Giphy CAPTURE](https://giphy.com/apps/giphycapture) or [Peek](https://github.com/phw/peek)

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). It can help to figure out who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them either through slack or by assigning them as a reviewer on the PR

2024-04-29 21:38 UTC, haynescd requested changes
Also some sonarCloud issues to relove

2024-04-29 21:38 UTC, haynescd commented on src/main/java/org/cbioportal/persistence/mybatis/StudyMyBatisRepository.java
> +        return studyMapper.getStudies(null, keyword, projection, pageSize, paginationCalculator.offset(pageSize, pageNumber),
PaginationCalculator::offset(pageSize, pageNumber)

2024-04-29 21:38 UTC, haynescd commented on src/main/java/org/cbioportal/service/impl/ClinicalDataServiceImpl.java
> +        )));
Just from observation. Our functions are usually bigger than they need to be. We should start focusing on keeping them small. With that, I would extract this out into a fn maybe buildSampleClinicalDataCollection

2024-04-29 21:38 UTC, haynescd commented on src/main/java/org/cbioportal/utils/Encoding.java
> +public class Encoding {
Encoder would be a better name

2024-04-29 21:38 UTC, haynescd commented on src/main/java/org/cbioportal/model/SampleClinicalDataCollection.java
> +public class SampleClinicalDataCollection {
Probably should start making Models not returned by MyBatis (Java Objs created by query results... Persistence layer) Immutable.

I would suggest making the class immutable (using a Builder Pattern to build the object)

2024-04-30 16:32 UTC, JREastonMarks commented
Weren't most, if not all, of these fixed with @fuzhaoyuan PR?

2024-04-30 16:34 UTC, haynescd commented on src/main/java/org/cbioportal/security/token/config/disable dat
These should not be added

2024-05-02 14:36 UTC, inodb commented
Correct @JREastonMarks - I think this is superseded by: https://github.com/cBioPortal/cbioportal/pull/10407

2024-05-02 14:36 UTC, closed without merging