Fix bug in data access token download.
cBioPortal/cbioportal pull request #7859
Opened 2020-09-02 20:26 UTC by ao508

Argument for 'allowRemovalOfExistingTokens' has been disconnected or
removed in some way from the frontend. 

When a user attempts to download a token from the
login dropdown menu, if the option to revoke existing tokens was
enabled then the user would be presented with an error if they had an
existing token instead of being issued a brand new one.

We have decided to simply remove this functionality and always issue a
new token on request.

Signed-off-by: Angelica Ochoa <15623749+ao508@users.noreply.github.com>

Fix # (see https://help.github.com/en/articles/closing-issues-using-keywords)

Describe changes proposed in this pull request:
- a
- b

# Checks
- [ ] Runs on heroku
- [ ] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.
- [ ] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [Giphy CAPTURE](https://giphy.com/apps/giphycapture) or [Peek](https://github.com/phw/peek)

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). It can help to figure out who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them either through slack or by assigning them as a reviewer on the PR

2020-09-03 09:03 UTC, sheridancbio requested changes
Looks good. Two test cases should be dropped because the expected exception will no longer occur. Also, if there are no other references in the code base to MaxNumberTokensExceededException, then that class should be dropped as well. Plus there is a function now that serves no purpose and should be dropped.

Overall comment: we are being expedient here and sacrificing a feature which is not known to be needed in order to resolve the current bug created (most likely) when the oauth2 tokens were introduced. The price we are paying by doing this is that now users will have no way to protect their tokens from being deleted when they are at their quota (under uuid token method). Even a valid (unexpired) token will be deleted at the moment that a user requests a new token when they are at their quota. It may be (I don't remember how the frontend is coded) that every time a user chooses the dropdown menu in the header to retrieve their token, they will cause a current valid token to be invalidated (deleted) and a fresh new token will replace it. Maybe that is the desired behavior, although I suspect some users will use the dropdown menu as a way to "check" what their current token is, which will instead result in invalidation of their current token and issuance of a new one. A different behavior could be coded in the frontend later, where current tokens were retrieved and displayed using the GET /data-access-tokens endpoint ... and then the user could choose to delete tokens or create new ones through some kind of UI which used the POST and DELETE methods available.

2020-09-03 09:08 UTC, sheridancbio commented on web/src/main/java/org/cbioportal/web/DataAccessTokenController.java
> +    private DataAccessToken createDataAccessToken(String userName) {
This function no longer serves any purpose. I suggest we drop this function and replace calls to it with a call to tokenService.createDataAccessToken(userName) instead.

2020-09-03 15:51 UTC, ao508 commented
@sheridancbio Addressed your comments, PR has been updated. Thanks!

2020-09-03 17:40 UTC, sheridancbio approved these changes
👍

2020-09-03 17:40 UTC, sheridancbio commented on src/main/resources/portal.properties.EXAMPLE
> -dat.uuid.revoke_other_tokens=true
great .. thanks for adding this change

2020-09-03 17:40 UTC, sheridancbio commented on web/src/main/java/org/cbioportal/web/error/GlobalExceptionHandler.java
> -    @ExceptionHandler(MaxNumberTokensExceededException.class)
nice cleaning this up too

2020-09-03 17:43 UTC, sheridancbio commented
@ao508 because this is a change to the cbioportal API definition we should have at least one reviewer from another institution before merging. Also .. we should remember to update the generated java / js api clients in other repos based on the change this will reflect in the swagger spec.

2020-09-07 08:42 UTC, pvannierop approved these changes
@ao508 Ah I think I have broken this functionality when the token download mechanism was changed. I approve you changes since The Hyve does not rely on this. But I would like to put out there the possibility of not dropping this functionality. I repair the frontend and have it send this parameter to the backend again. Your PR will not be needed in that case. I am willing to help out here. Just let me know what you prefer.

2020-09-08 15:05 UTC, ao508 commented
@pvannierop Just finished dicussing with Ben and I've confirmed that we're okay dropping this functionality. Thanks for the review!

2020-09-08 15:28 UTC, ao508 commented
@n1zea144 This is okay to merge now

2020-09-08 17:19 UTC, ao508 commented
@inodb I see the "labeler" and "end_to_end_tests_localdb" checks failing for multiple prs, is this already a known issue that can be ignored for now ?

2020-09-09 07:00 UTC, pvannierop commented
@inodb @ao508 @sheridancbio I will fix the e2e-tests today. We made modifications study_es_0 and this broke some tests. Does not affect functionality.

2020-09-09 13:53 UTC, merged