(Generic Assay) Import Patient Level data
cBioPortal/cbioportal pull request #8509
Opened 2021-04-13 07:02 UTC by dippindots

Fix #8459 

Describe changes proposed in this pull request:
- Include database migration (new field in `genetic_profile`: `PATIENT_LEVEL`, default value is `false`)
- Data validator
- New data importer: `ImportGenericAssayPatientLevelData`
- Update logic in `ExpressionEnrichmentServiceImpl.java` to filter samples by unique patient

2021-04-19 17:01 UTC, n1zea144 requested changes
I'm not entirely sure why there is `patient_level` generic assay data.  It seems like when patient_level is true, data is propagated across all samples.  Is patient level data supported to make it more convenient to apply a measure across all samples that belong to the patient?

2021-04-19 20:40 UTC, dippindots commented
@n1zea144 Thanks for your review, this was part of our discussion with @kalletlak and @jjgao. 
We thought about a few different ways to support `patient level` data. And Rest of them will require much more time to implement, so we decided to import `patient level` data as `sample level` data since we can reuse all existing implementation and just require a little bit changes to the front-end. https://github.com/cBioPortal/cbioportal/issues/8450#issuecomment-804297016

2021-04-20 15:06 UTC, n1zea144 commented
If patient level data will always be imported as sample level data, why not change the file format to accept sample ids instead of patient ids and get rid of the patient level boolean in the meta properties flag.  It would make the code/documentation less complicated? cc: @kalletlak @jjgao

2021-04-28 18:25 UTC, dippindots commented on docs/File-Formats.md
> +Data will be considered as sample level data if `patient_level` is not specified or is `false`. And patients or samples need to be included in clinical data file. Please check the [Clinical Data](#cl
Changed to suggested text, UI will not be affected visually, just logic for statistics will change.

2021-04-28 18:28 UTC, dippindots commented on core/src/main/java/org/mskcc/cbio/portal/scripts/ImportGenericAssayPatientLevelData.java
> +            featureColNames.addAll(Arrays.asList(propertyNames));
No, `genericEntityProperties` is a string in meta files that defines additional columns for `Generic Assay`. `ENTITY_STABLE_ID` is a fixed column which will not show up in that string.

2021-04-28 18:36 UTC, dippindots commented on core/src/main/java/org/mskcc/cbio/portal/scripts/ImportGenericAssayPatientLevelData.java
> +            int lenParts = parts.length;
This is useless, removed.

2021-04-29 22:26 UTC, n1zea144 requested changes

2021-04-29 22:26 UTC, n1zea144 commented on docs/File-Formats.md
> +Generic Assay data will be considered `sample_level` data if the `patient_level` property is missing or set to `false`. In addition, the patient or sample identifiers need to be include in the [Clini
Minor typo s/include/included/

2021-04-30 15:02 UTC, dippindots commented on docs/File-Formats.md
> +Generic Assay data will be considered `sample_level` data if the `patient_level` property is missing or set to `false`. In addition, the patient or sample identifiers need to be include in the [Clini
fixed, thanks!

2021-06-10 16:07 UTC, n1zea144 approved these changes

2021-06-14 16:06 UTC, kalletlak commented on service/src/main/java/org/cbioportal/service/impl/ExpressionEnrichmentServiceImpl.java
> +                    } else {
may be 
```
if (!patientSet.contains(sampleIdToPatientIdMap.get(caseIdentifier.getCaseId()))) {
    identifierListUniqueByPatientId.add(caseIdentifier);
    patientSet.add(sampleIdToPatientIdMap.get(caseIdentifier.getCaseId()));
}
```

2021-06-14 18:41 UTC, dippindots commented on core/src/main/scripts/importer/validateData.py
> +    def checkId(self):
Sure, I can do that

2021-06-14 20:15 UTC, kalletlak approved these changes

2021-07-20 15:22 UTC, merged

2024-05-17 10:27 UTC, pieterlukasse commented
@n1zea144 @kalletlak I think the questions @n1zea144 raised make sense, but I don't see an answer to the last ones. Can you please add the rationale for pushing forward with this change? Why not just upload the same data through the existing sample level format, if it ends up in this way in the DB anyway?