Docs update for unauthorized studies portal prop
cBioPortal/cbioportal pull request #9272
Opened 2022-01-31 15:16 UTC by dianab0

Updated portal property reference docs for the configuration of a global message for unauthorized studies.

This docs update is related to PR https://github.com/cBioPortal/cbioportal-frontend/pull/4138

2022-02-01 08:25 UTC, pvannierop requested changes

2022-02-01 12:28 UTC, dianab0 commented on docs/portal.properties-Reference.md
> +
Removed

2022-02-01 12:28 UTC, dianab0 commented on docs/portal.properties-Reference.md
> +skin.home_page.unauthorized_studies_global_message=The study {$.studyId} is unauthorized. You need to request access to {$.Owner.email}.
Done

2022-02-01 12:28 UTC, dianab0 commented
Added changes from review under the same commit

2022-02-02 02:39 UTC, dippindots approved these changes
@dianab0 Looks good to me, Are the related changes already merged? Could you mention that pr in the description if it's already merged?

2022-02-05 09:28 UTC, dianab0 commented
@dippindots , thank you, no, the PR containing related changes wasn't merged yet https://github.com/cBioPortal/cbioportal-frontend/pull/4138

2022-02-15 09:29 UTC, pvannierop approved these changes
Looks good.

2022-02-16 20:17 UTC, dianab0 commented
@dippindots , the PR containing related changes (https://github.com/cBioPortal/cbioportal-frontend/pull/4171) has been merged, so this one is ready to be merged as well. Thank you.

2022-02-21 16:10 UTC, merged