Update minimal MAF format documentation
cBioPortal/cbioportal pull request #9656
Opened 2022-07-05 17:10 UTC by rmadupuri

Fix #9623

2022-07-06 17:39 UTC, inodb commented on docs/File-Formats.md
> +13. **Tumor_Seq_Allele2 (Required)**: Primary data genotype.
So should it be `Tumor_Seq_Allele1` instead?

2022-07-06 18:01 UTC, rmadupuri commented on docs/File-Formats.md
> +13. **Tumor_Seq_Allele2 (Required)**: Primary data genotype.
@inodb, we usually consider the `Reference_Allele` and `Tumor_Seq_Alelle2` as the reference and variant alleles. And all the MAFs from public studies are built on that. The values in `Tumor_Seq_Alelle1` are the same as the `Reference_Allele` column.

2022-07-06 18:03 UTC, rmadupuri commented on docs/File-Formats.md
> +13. **Tumor_Seq_Allele2 (Required)**: Primary data genotype.
I think the importer looks at `Reference_Allele` and `Tumor_Seq_Alelle2` columns too - but need to double check on that.

2022-07-12 17:14 UTC, inodb commented on docs/File-Formats.md
> +13. **Tumor_Seq_Allele2 (Required)**: Primary data genotype.
gotcha ok - thanks!

2022-07-12 17:22 UTC, inodb commented on docs/File-Formats.md
> +9. **t_ref_count (Optional, but recommended)**: Reference allele count (tumor).
great that it says recommended 👍

2022-07-12 17:23 UTC, inodb commented on docs/File-Formats.md
> +11. **SWISSPROT (Optional)**: (annotation column) UniProtKB/SWISS-PROT name (formerly called ID) or accession code depending on the value of the `swissprot_identifier` metadatum, e.g. O11H1_HUMAN or
are these still used? I don't think so? As far as I know the protein position is annotated on the fly using genome nexus? CC @onursumer @leexgh

2022-07-12 17:24 UTC, inodb commented on docs/File-Formats.md
> +9. **t_ref_count (Optional, but recommended)**: Reference allele count (tumor).
It seems like `t_alt_count` and `t_ref_count` are listed twice? They are also listed below

2022-07-12 17:39 UTC, inodb requested changes
Thanks so much @rmadupuri ! This is a great improvement

Some small comments. There are a lot of columns listed still that are optional and ignored. I propose that we make it a bit more clear in the text which ones are "(optional - recommend)" and "(optional - ignored)".

It could also help to list the true minimum required comments and maybe point to an example file such as:

https://github.com/genome-nexus/genome-nexus-annotation-pipeline/blob/master/test/data/minimal_example.in.txt

And then an example that e.g. has the full TCGA spec

It could be good to work with @ozguzMete here to make sure the documentation aligns with the genome-nexus-annotation-pipeline implementation

2022-07-19 22:29 UTC, inodb commented
Let's merge as is and follow up with other improvements later

2022-07-19 22:29 UTC, inodb approved these changes

2022-07-19 22:29 UTC, merged